export const siteConfig = {
  domain: "novaorganizasyon7.com.tr",
  url: "https://novaorganizasyon7.com.tr",
  company: {
    name: "NOVA ORGANİZASYON",
    legalName: "NOVA GLOBAL BİLİŞİM TURİZM ORGANİZASYON VE DANIŞMANLIK LİMİTED ŞİRKETİ",
    mersis: "0632159982000001",
    taxOffice: "Antalya Kurumlar V.D.",
    taxNo: "632 159 9820",
    city: "Kepez / ANTALYA",
    address: "Kültür Mah. 3856 Sk. 1. Yeşil Yayla Apt. No:2 İç Kapı No:1 Kepez / Antalya",
    director: "Çelebi ASAL",
    tradeRegistry: "Antalya Ticaret Sicili Müdürlüğü (TTSG: 11.09.2026, Sayı: 11164)",
  },
  contact: {
    phone: "0505 410 48 00",
    phoneIntl: "+90 505 410 48 00",
    phoneRaw: "905054104800",
    secondaryPhone: "0505 410 48 00",
    email: "iknovaofis@gmail.com",
    department: "Saha Operasyon & Danışmanlık Masası",
    titleTR: "Saha Operasyon Masası",
    titleEN: "Field Operations Dispatch",
  },
  social: {
    instagram: "novaofisss",
    instagramUrl: "https://instagram.com/novaofisss",
    whatsappUrl: "https://wa.me/905054104800",
  },
  location: {
    cityTR: "Antalya Merkez / Türkiye",
    cityEN: "Antalya Central / Turkey",
    regionsTR: "ANFAŞ Fuar Merkezi, Belek, Kundu, Kemer, Lara, Alanya",
    regionsEN: "ANFAS Expo, Belek, Kundu, Kemer, Lara, Alanya",
  },
} as const;
